### ISSUE TITLE
Set up pre-commit hooks using Prettier and husky for both Frontend and backend folder

### ISSUE THREAD

**Issue by adarshanand67** [adarshanand67/ShareMe#21]
https://www.youtube.com/watch?v=ZXW6Jn6or1w

**Comment by Laxmankohar** [comment]
Hey @adarshanand67 , I would like to work on this issue under JWOC. Can you please assign it ot me?

**Comment by Laxmankohar** [comment]
Hey @adarshanand67  bro, have a look and confirm sothat i can make pr.

![image](https://user-images.githubusercontent.com/73365025/221376594-6dafc3fb-0f1a-472e-836a-4ef42027a311.png)

![image](https://user-images.githubusercontent.com/73365025/221376566-41536777-feb5-4532-be00-65af3f32f069.png)

**Comment by Laxmankohar** [comment]
@adarshanand67  bro, have a look on the above ss.

**Comment by adarshanand67** [comment]
Make a PR

**Comment by adarshanand67** [comment]
Looks good to me

**Comment by Laxmankohar** [comment]
> Make a PR

ok.

**Comment by adarshanand67** [comment]
Closed by #59
