### ISSUE TITLE
Make the search Term accept all charecters

### ISSUE THREAD

**Issue by adarshanand67** [adarshanand67/ShareMe#29]
<img src="https://i.imgur.com/NEkeZ4N.png">

**Comment by safinghoghabori** [comment]
I want to work on this issue under JWOC

**Comment by vk20july** [comment]
I want to work on this issue under JWOC

**Comment by adarshanand67** [comment]
> I want to work on this issue under JWOC
> 

Assigned

**Comment by Saedbhati** [comment]
Assign me

**Comment by bcsamrudh** [comment]
@adarshanand67. I would love to contribute to this issue.

**Comment by adarshanand67** [comment]
This fixed - https://github.com/adarshanand67/ShareMe/commit/3a3735c0badaa27d37fca415254826e632f5b15a
