### ISSUE TITLE
Cancel button while creating pin

### ISSUE THREAD

**Issue by suryanshsoni120** [adarshanand67/ShareMe#36]
If a user creates a new pin but wants to discard it, there should be a cancel button to support this.

**Comment by suryanshsoni120** [comment]
I would like to work on this issue.

**Comment by adarshanand67** [comment]
but there is already delete button present if you hover over a pin

**Comment by suryanshsoni120** [comment]
**Adding the cancel button like this**
![image](https://user-images.githubusercontent.com/63662732/219021399-e11416e6-88f9-4e66-9311-888b251d4e92.png)

**Comment by adarshanand67** [comment]
Alright I can add this under easy issue, Also if possible can you change the UI of form to look more aesthetic?

**Comment by adarshanand67** [comment]
@suryanshsoni120
