### ISSUE TITLE
Favicon replacement required

### ISSUE THREAD

**Issue by tmsagarofficial** [adarshanand67/ShareMe#54]
I want to let u know that the current favicon is not displayed correctly in all browsers........
because it has white background along with the logo
![image](https://user-images.githubusercontent.com/110724849/221195887-83beeb39-e09f-4f42-a009-fbb3009fbaa7.png)
![image](https://user-images.githubusercontent.com/110724849/221195903-268b933c-a7d4-4b5d-977f-82043e05d285.png)

i would love to work on this under jwoc
@adarshanand67

**Comment by adarshanand67** [comment]
Yup you can work on this - nice observation

**Comment by tmsagarofficial** [comment]
check it out @adarshanand67 and also check my comments here at #16 before merging with labels

**Comment by tmsagarofficial** [comment]
@adarshanand67 Bro pls check this out ASAP
