### ISSUE TITLE
Display the User Profile Dashboard on the navbar

### ISSUE THREAD

**Issue by adarshanand67** [adarshanand67/ShareMe#6]

**Comment by suryanshsoni120** [comment]
I would like to work on this issue. Can you please provide some more info regarding this issue?

**Comment by adarshanand67** [comment]
You should have a button that redirects to userProfile when clicked and it should have you avatart as a button

**Comment by suryanshsoni120** [comment]
I want to work on this issue under JWOC

**Comment by adarshanand67** [comment]
You have 1 day time, do comment if help needed

**Comment by abhrajit117** [comment]
I want to work on this assign me thisone

**Comment by Gun2902** [comment]
can u assign me this issue
