### ISSUE TITLE
Create a video walkthrough of the Website

### ISSUE THREAD

**Issue by adarshanand67** [adarshanand67/ShareMe#8]
The mentee should have good video editing skills and can add stock music

**Comment by VaibhavTalkhande** [comment]
Can I work on it under JWOC

**Comment by adarshanand67** [comment]
Ok

**Comment by VaibhavTalkhande** [comment]
I have done almost part made video walkthrough for pc and mobile.
Can I submit it by tomorrow because exam .

**Comment by adarshanand67** [comment]
Sure ATB

**Comment by VaibhavTalkhande** [comment]
done

**Comment by VaibhavTalkhande** [comment]
have sent a pr right now
