### ISSUE TITLE
Migrate the frontend project from CRA to Vite

### ISSUE THREAD

**Issue by adarshanand67** [adarshanand67/ShareMe#9]
From Create react app  to Vite.
Make Sure you do not produce breaking changes

**Comment by adarshanand67** [comment]
https://github.com/coryhouse/reactjsconsulting/issues/139

**Comment by adarshanand67** [comment]
https://blog.logrocket.com/vite-3-vs-create-react-app-comparison-migration-guide/#migrating-a-create-react-app-project-to-vite

**Comment by shivam1317** [comment]
Can i work on this issue?

**Comment by adarshanand67** [comment]
> Can i work on this issue?

Go ahead, make sure to do changes in .env files as well
